export const CategoryList = [
  "Advertising/Marketing",
  "Album",
  "Amateur Sports Team",
  "Apartment & Condo Building",
  "Appliance Repair Service",
  "App Page",
  "Architectural Designer",
  "Art",
  "Artist",
  "Arts & Entertainment",
  "Athlete",
  "Automotive Repair Shop",
  "Baby & Children’s Clothing Store",
  "Baby Goods/Kids Goods",
  "Bar",
  "Beauty, Cosmetic & Personal Care",
  "Beauty Salon",
  "Book",
  "Business Center",
  "Business Service",
  "Camera/Photo",
  "Canoe & Kayak Rental",
  "Chicken Joint",
  "Church of Christ",
  "Church of Jesus Christ of Latter-day Saints",
  "Clothing (Brand)",
  "Clothing Store",
  "College & University",
  "Commercial & Industrial",
  "Commercial & Industrial Equipment Supplier",
  "Commercial Bank",
  "Commercial Equipment",
  "Commercial Real Estate Agency",
  "Commercial Truck Dealership",
  "Community",
  "Community Organization",
  "Consulting Agency",
  "Contractor",
  "Convenience Store",
  "Credit Union",
  "Doctor",
    "Deli",
    "Dancer",
    "Design & Fashion",
    "Dessert Shop",
    "Discount Store",
    "Dorm",
    "E-Cigarette Store",
"E-commerce Website",
"Education",
"Engineering Service",
"Entertainment Website",
"Entrepreneur",
"Episode",
"Event",
"Family Style Restaurant",
"Fashion Designer",
"Fashion Model",
"Fast Food Restaurant",
"Financial Service",
"Food & Beverage",
"Food Stand",
"Footwear Store",
"Gamer",
"Games/Toys",
"Gaming Video Creator",
"Government Organization",
"Graphic Designer",
'Grocery Store',
"Hardware Store",
"Health/Beauty",
"Heating, Ventilating & Air Conditioning Service",
"Home Decor",
"Home Improvement",
"Hospital",
"Hotel",
"Hotel & Lodging",
"Ice Cream Shop",
"In-Home Service",
"Industrial Company",
"Information Technology Company",
"Insurance Company",
"Interior Design Studio",
"Internet Company",
"Internet Marketing Service",
"Japanese Restaurant",
"Jazz & Blues Club",
"Jewelry/Watches",
'Jewelry & Watches Company',
"Journalist",
"Just For Fun",
"Karaoke",
"Kennel",
"Kitchen & Bath Contractor",
"Kitchen/Cooking",
"Korean Restaurant",
"Landmark & Historical Place",
"Lawyer & Law Firm",
"Library",
'Loan Service',
'Local Service',
"Lumber Yard",
"Marketing Agency",
'Media',
"Media/News Company",
'Medical Center',
'Medical School',
"Men’s Clothing Store",
"Mental Health Service",
"Movie",
'Musician/Band',
"Music Lessons & Instruction School",
'Music Video',
'News & Media Website',
'Newspaper',
'Nonprofit Organization',
'Non-Governmental Organization (NGO)',
'Not a Business',
'Nursing Agency',
"Obstetrician-Gynecologist (OBGYN)",
'Office Equipment Store',
'Office Supplies',
'Optician',
'Optometrist',
'Outdoor & Sporting Goods Company',
'Personal Blog',
'Petting Zoo',
'Photographer',
'Product/Service',
'Public & Government Service',
'Public Figure',
'Public Utility Company',
'Quay',
'Real Estate',
'Real Estate Agent',
'Real Estate Appraiser',
'Real Estate Company',
'Real Estate Developer',
'Record Label',
'Religious Center',
'Religious Organization',
'Residence',
'Restaurant',
'Retail Bank',
'School',
'Science, Technology & Engineering',
'Shopping & Retail',
'Shopping District',
'Shopping Mall',
'Smoothie & Juice Bar',
'Song',
'Specialty School',
'Sports & Recreation',
'Sports League',
'Sports Team',
'Teens & Kids Website',
'Telemarketing Service',
'Tire Dealer & Repair Shop',
'Trade School',
'Traffic School',
'Train Station',
'Tutor/Teacher',
'TV Channel',
'TV Network',
'TV Show',
'Udon Restaurant',
'Ukranian Restaurant',
'Unagi Restaurant',
'Uniform Supplier',
'Urban Farm',
'Vacation Home Rental',
'Veterinarian',
'Video Creator',
'Video Game',
'Visual Arts',
'Web Designer',
'Website',
'Wedding Planning Service',
'Winery/Vineyard',
'Women’s Clothing Store',
'Women’s Health Clinic',
'Writer',
'Xinjiang Restaurant',
'Yakiniku Restaurant',
'Yakitori Restaurant',
'Yoga Studio',
'Yoshoku Restaurant',
'Youth Organization',
'Zhejiang Restaurant',
'Zoo'
];

